### ISSUE TITLE
chat: chat UI loses scrollback on every page reload

### ISSUE THREAD

**Issue by vvisigoth** [urbit/urbit#1824]
After page reload
<img width="1440" alt="Screenshot 2019-10-15 15 52 33" src="https://user-images.githubusercontent.com/1609955/66875639-e425e400-ef63-11e9-9d3d-78fa596e83da.png">

**Comment by vvisigoth** [comment]
To be clear, the above screen was full of messages

**Comment by loganallenc** [comment]
Will be fixed as soon as https://github.com/urbit/urbit/pull/1825 is merged

**Comment by jtobin** [comment]
(Presumably) fixed by #1825.

**Comment by hrharder** [comment]
@jtobin It's possible my (0.9) ship didn't receive the OTA somehow, but this is still an issue for me.

**Comment by vvisigoth** [comment]
@hrharder looks like you didn't get the OTA because your sponsoer (~fiprun) is offline. Please email us at support@urbit.org I have a fix.

**Comment by hrharder** [comment]
Thanks. Following up in urbit-help so consider this resolved (for any future readers).
