### ISSUE TITLE
code 32000

### ISSUE THREAD

**Issue by custom-jonathan** [urbit/urbit#2088]
Just received this amongst a slew of "still trying/ok" messages:

```[%error-results i=[id='logs by hash' code='-32000' message='unknown block'] t=~]```

**Comment by custom-jonathan** [comment]
Including this screen shot in case it's all related: 
![image](https://user-images.githubusercontent.com/51895363/70740429-c3b5a400-1cde-11ea-8b0a-974d7ead8d1e.png)

**Comment by custom-jonathan** [comment]
And my ship has been randomly becoming unresponsive. Can't switch between dojo or chat. I'll only be aware of it when I try to refresh my landscape and it sits on "thinking." I'll ssh into my droplet, and I can't do anything after reattaching to my screen. I'll ctl+z 2x to slam the ship down, and restart it.

Don't know if these should all go in separate issues, or if they're multiple symptoms of the same problem.

**Comment by philipcmonk** [comment]
The `error-results` printf is harmless, silenced on master, will go out in the next OTA (probably tonight ?).

The not-responding/is ok is probably #2071, which should also go out in the next OTA.  I had this on ~wicdev and deployed that and it fixed it.

The hanging is one @joemfb is tracking down.  The first step is getting debug symbols into the build, which is... you guessed it, in the next update (not OTA because it's an update to the interpreter, so it'll be 0.10.2).

**Comment by joemfb** [comment]
The hanging (or at least some of it) should be fixed by #2069, which will be in the next update.

**Comment by custom-jonathan** [comment]
Still getting the slew of ok/still trying. Did the OTA go out and I'm missing it from my star?

**Comment by philipcmonk** [comment]
Hasn't gone out yet, I'm hoping to push it out tonight

**Comment by custom-jonathan** [comment]
Got the update on ~minder-folden & ~talleg-botsug. Both have the .of4bg hash but ~minder is still getting this kind of stuff:

```
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
; ~talleg-botsug not responding still trying
; ~talleg-botsug is ok
; ~novlud-padtyv not responding still trying
; ~novlud-padtyv is ok
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
[%received-event-for-nonexistent-channel '1575514789219-0aa53e']
ames: strange wake queue, expected 47, got [message-num=46 fragment-num=406]
; ~talleg-botsug not responding still trying
; ~talleg-botsug is ok
```

**Comment by philipcmonk** [comment]
The %received-event error is unusual, but just means there's a garbage subscription still around.  Harmless.

The "strange wake" notification indicates we still had something in our packet queue after it had already been acknowledged.  @belisarius, we need to isolate what causes this.  Regardless, that printf indicates it's repairing the state, so it shouldn't be a problem.

**Comment by custom-jonathan** [comment]
With #2098 we can turn off the `%received-event` notifications with `|knob`? Do we have to `%hush` the whole alert? Or just use `%received-event`? I've tried 'em both and I'm still getting alert after alert in my client.

**Comment by philipcmonk** [comment]
With #2098, you will be able to run `|knob %eyre-no-channel %hush` to silence it.  However, it hasn't been deployed yet.
