### ISSUE TITLE
metadata-store: retains group metadata after deletion

### ISSUE THREAD

**Issue by galenwp** [urbit/urbit#2992]
**Describe the bug**
When I go to filter on the 'Tlon' group, I see two results. Since we migrated the group at one point, I think this is the old one. But it no longer exists in my 'all groups' view.

**To Reproduce**
This seems specific to the Tlon group, and not to any deleted group

1. Click on the 'all groups' dropdown
2. Filter on 'Tlon'
3. See 'Tlon' twice
4. Click on the 'wrong' one and have the filter just make all groups disappear

**Expected behavior**
There should only be one Tlon group, since I'm only in one.

**Screenshots**
<img width="209" alt="Screen Shot 2020-06-08 at 6 04 54 AM" src="https://user-images.githubusercontent.com/1467211/84033966-81e47e00-a94e-11ea-9765-ce6c70562a6c.png">
<img width="323" alt="Screen Shot 2020-06-08 at 6 01 21 AM" src="https://user-images.githubusercontent.com/1467211/84033970-827d1480-a94e-11ea-8b49-cdf6374ee4c1.png">

While we're at it, it'd be nice if we didn't spellcheck the group name in the filter box.

**Comment by matildepark** [comment]
We're clearly retaining the `metadata-store` entry for the group (which is what we search through in that component). @loganallenc comments on appropriate behaviour?

**Comment by matildepark** [comment]
Amending title because this is a metadata-store issue and the group filter is no longer in Landscape.

**Comment by matildepark** [comment]
Bumping this a bit because it's more pressing in our current groups layout, where links to the group persist but lead nowhere. @tacryt-socryp let's chat about how some of the metadata work you're thinking about might incorporate this?

**Comment by matildepark** [comment]
Implicit part of the modernisation work in urbit/landscape#72.

**Comment by tacryt-socryp** [comment]
Fixed in #4044.

**Comment by ycl924** [comment]
I have metadata remaining from groups I left, and :metadata-store [%cleanup /~ship/groupname] isn't helping (it still shows up on the debug page). I think that's what preventing me from rejoining the groups as stated in the other issue. What can I do?

**Comment by matildepark** [comment]
Given that all paths you're providing are seemingly doing *nothing* it's possible you're passing the wrong paths. That said I'm unsure a cleanup is necessary here. Metadata won't prohibit a group join.

**Comment by tacryt-socryp** [comment]
@ycl924 you could try [%cleanup /ship/~insert-ship/insert-group]

**Comment by tacryt-socryp** [comment]
Can't repro on my ship anymore since #4044. Tested just now.

**Comment by tacryt-socryp** [comment]
I have a new issue, though, which is that the observer-failed for some reason in the middle of the `%on-group-leave` thread. Investigating.

**Comment by matildepark** [comment]
Fixed in #4044.
