### ISSUE TITLE
Issue joining groups from Landscape

### ISSUE THREAD

**Issue by jamesacklin** [urbit/urbit#3227]
**Describe the bug**
When joining a group in Landscape, the "Joining group..." spinner spins forever, a `poke failed` error appears from my ship, and I am not able to join a group. I recently breached, am running a new pier, and am up to date on OTAs.

**To Reproduce**
1. Navigate to "All Groups," select "Manage All Groups," and select "Join Group."
2. Enter `~bitbet-bolbel/urbit-community` in the group name field.
3. Select "Join Group."
4. See "Joining group..." loader.
5. Tab over to Terminal to running ship; note the `poke failed` error.

**Expected behavior**
I expected to join the group.

**Screenshots**
![image](https://user-images.githubusercontent.com/748181/88955313-bf3bfc80-d269-11ea-9729-acd1ed039429.png)

Stack trace from ship:
```
poke failed from %contact-view on wire /
/lib/pull-hook/hoon:<[228 7].[232 37]>
[entity=~bitbet-bolbel name=%urbit-community]
/lib/pull-hook/hoon:<[227 7].[232 37]>
/lib/pull-hook/hoon:<[222 13].[222 27]>
/lib/pull-hook/hoon:<[221 5].[224 7]>
/lib/pull-hook/hoon:<[220 5].[238 7]>
/lib/pull-hook/hoon:<[219 5].[238 7]>
/lib/pull-hook/hoon:<[138 9].[138 46]>
/lib/pull-hook/hoon:<[137 7].[139 19]>
/lib/pull-hook/hoon:<[133 7].[139 19]>
/lib/pull-hook/hoon:<[132 7].[139 19]>
/lib/pull-hook/hoon:<[131 7].[139 19]>
```

`+trouble` output:
```
[ [%base-hash 0v14.6jq85.45bbd.olulk.d6ahq.p6q00.duosn.0uu5d.grv3j.9i7m1.n91u1]
  [%home-hash 0v14.6jq85.45bbd.olulk.d6ahq.p6q00.duosn.0uu5d.grv3j.9i7m1.n91u1]
  [%kids-hash 0v14.6jq85.45bbd.olulk.d6ahq.p6q00.duosn.0uu5d.grv3j.9i7m1.n91u1]
  [%glob-hash 0v5.m40lm.ha96c.aavqb.57scm.222e7 %done]
  [%our ship=~rilfun-lidlen point='584450466' life=[~ 3] rift=[~ 1]]
  [%sponsor ship=~marnus point='418' life=[~ 1] rift=[~ 4]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1 LTS
 - Browser: Chrome64 84.0.4147.105
 - Base hash: `n91u1`

**Comment by matildepark** [comment]
@liam-fitzgerald I recall we found a fix for this a while ago — @jamesacklin might be a "straight from Ford Fusion to post-groups refactor" case. Can you refresh us on what needs doing in these cases?

**Comment by darbyn-litbel** [comment]
Hi, I'm experience the same issue with very similar behavior when trying to join groups.

ship stack trace:
```
poke failed from %contact-view on wire /
/lib/pull-hook/hoon:<[228 7].[232 37]>
[entity=~hiddev-dannut name=%new-hooniverse]
/lib/pull-hook/hoon:<[227 7].[232 37]>
/lib/pull-hook/hoon:<[222 13].[222 27]>
/lib/pull-hook/hoon:<[221 5].[224 7]>
/lib/pull-hook/hoon:<[220 5].[238 7]>
/lib/pull-hook/hoon:<[219 5].[238 7]>
/lib/pull-hook/hoon:<[138 9].[138 46]>
/lib/pull-hook/hoon:<[137 7].[139 19]>
/lib/pull-hook/hoon:<[133 7].[139 19]>
/lib/pull-hook/hoon:<[132 7].[139 19]>
/lib/pull-hook/hoon:<[131 7].[139 19]>
```

js console:

![image](https://user-images.githubusercontent.com/69164735/89212132-cd469180-d577-11ea-8fce-9a850f4e4025.png)

`:group-store +dbug`
```>   [ %1
    groups
  { [ p=[entity=~darbyn-litbel name=%~2020.8.03..05.56.37]
      q=[members={} tags={[p=%admin q={~darbyn-litbel}]} policy=[%open ban-ranks={} banned={}] hidden=%.y]
    ]
  }
]
> :group-store +dbug
>=
```

OS: osx 10.13.6
Browser: Version 1.10.93 Chromium: 83.0.4103.106 (Official Build) (64-bit)
Base hash: `bmhb4`

**Comment by liam-fitzgerald** [comment]
can either of you run `:group-pull-hook +dbug` and post output?

**Comment by jamesacklin** [comment]
@liam-fitzgerald Sure thing.

```
>   [ %0
  tracking={[p=[entity=~bitbet-bolbel name=%urbit-community] q=~bitbet-bolbel]}
  inner-state=[#t/$~ q=0]
]
> :group-pull-hook +dbug
>=
```

**Comment by darbyn-litbel** [comment]
```
>   [ %0
    tracking
  { [p=[entity=~hiddev-dannut name=%new-hooniverse] q=~hiddev-dannut]
    [p=[entity=~hiddev-dannut name=%hooniverse] q=~hiddev-dannut]
  }
  inner-state=[#t/$~ q=0]
]
> :group-pull-hook +dbug
>=
```

**Comment by jalehman** [comment]
Just had what may be another occurrence of this issue similar to the one that @darbyn-litbel experienced. Occurred upon accepting the invite to a group from within Landscape. Below is the output received from my ship and the result of `:group-pull-hook +dbug`

```
crud: %eyre-no-channel event failed
id='1593964130838-d4d04a'
poke failed from %contact-view on wire /join-group/ship/~dopzod/provider-standards-organization
poke-ack
/lib/push-hook/hoon:<[204 5].[208 84]>
/lib/push-hook/hoon:<[203 5].[208 84]>
/lib/push-hook/hoon:<[134 11].[134 32]>
/lib/push-hook/hoon:<[133 9].[135 21]>
/lib/push-hook/hoon:<[132 7].[139 19]>
/lib/push-hook/hoon:<[126 7].[139 19]>
/lib/push-hook/hoon:<[125 7].[139 19]>
poke failed from %contact-view on wire /join-group/ship/~dopzod/provider-standards-organization
poke-ack
/lib/push-hook/hoon:<[204 5].[208 84]>
/lib/push-hook/hoon:<[203 5].[208 84]>
/lib/push-hook/hoon:<[134 11].[134 32]>
/lib/push-hook/hoon:<[133 9].[135 21]>
/lib/push-hook/hoon:<[132 7].[139 19]>
/lib/push-hook/hoon:<[126 7].[139 19]>
/lib/push-hook/hoon:<[125 7].[139 19]>
; ~pilnys-pattex is ok
~wolref-podlex:dojo>
```

```
>   [ %0
    tracking
  { [p=[entity=~nibset-napwyn name=%remote-life] q=~nibset-napwyn]
    [p=[entity=~hiddev-dannut name=%new-hooniverse] q=~hiddev-dannut]
    [p=[entity=~rivpyl-sidfyl name=%martian-cinema] q=~rivpyl-sidfyl]
    [p=[entity=~norbet-sommud name=%postwoke] q=~norbet-sommud]
    [p=[entity=~sopped-mirdeb name=%dm--wolref-podlex] q=~sopped-mirdeb]
    [p=[entity=~dabben-larbet name=%tlon] q=~dabben-larbet]
    [p=[entity=~dalten name=%dalten-collective] q=~dalten]
    [p=[entity=~bitpyx-dildus name=%hoon-school-alumni] q=~bitpyx-dildus]
    [p=[entity=~sabbus name=%new-computer-working-group] q=~sabbus]
    [p=[entity=~hastuc-dibtux name=%pharma] q=~hastuc-dibtux]
    [p=[entity=~larsum-tacrus name=%dm--wolref-podlex] q=~larsum-tacrus]
    [p=[entity=~paldev name=%group] q=~paldev]
    [p=[entity=~siddef name=%~siddef-community] q=~siddef]
    [p=[entity=~littel-wolfur name=%----the-forge] q=~littel-wolfur]
    [p=[entity=~tirlyn-todnex name=%dm--wolref-podlex] q=~tirlyn-todnex]
    [p=[entity=~sicdev-pilnup name=%dm--wolref-podlex] q=~sicdev-pilnup]
    [p=[entity=~bonnyt-pollen name=%information-gathering-4229] q=~bonnyt-pollen]
    [p=[entity=~bonnyt-pollen name=%personal-development-and-transformation] q=~bonnyt-pollen]
    [p=[entity=~bitbet-bolbel name=%urbit-community] q=~bitbet-bolbel]
    [p=[entity=~minder-folden name=%---the-sanctorium] q=~minder-folden]
    [p=[entity=~timluc-miptev name=%overhead-on-urbit] q=~timluc-miptev]
    [p=[entity=~norsyr-torryn name=%on-urbit-and-bitcoin] q=~norsyr-torryn]
    [p=[entity=~dalten name=%collective] q=~dalten]
    [p=[entity=~nartes-fasrum name=%urbytes] q=~nartes-fasrum]
    [p=[entity=~litpub name=%urth] q=~litpub]
    [p=[entity=~bitpyx-dildus name=%tlon-movie-club] q=~bitpyx-dildus]
    [p=[entity=~timluc-miptev name=%the-collapse] q=~timluc-miptev]
    [p=[entity=~darlur name=%bookends] q=~darlur]
  }
  inner-state=[#t/$~ q=0]
]
> :group-pull-hook +dbug
>=
```

OS: Ubuntu 18.04.4 LTS (GNU/Linux 4.15.0-66-generic x86_64)
Binary: 0.10.8
Base Hash: bmhb4

**Comment by matildepark** [comment]
Thanks @jalehman — pinging @liam-fitzgerald, whenever you're in again, can you see if there's a troubleshooting fix we can issue for this?

**Comment by SaulMoonves** [comment]
Similar issue except attempting to join private group from invitation:

```poke failed from %contact-view on wire /join-group/ship/~dopzod/provider-standards-organization
poke-ack
/lib/push-hook/hoon:<[204 5].[208 84]>
/lib/push-hook/hoon:<[203 5].[208 84]>
/lib/push-hook/hoon:<[134 11].[134 32]>
/lib/push-hook/hoon:<[133 9].[135 21]>
/lib/push-hook/hoon:<[132 7].[139 19]>
/lib/push-hook/hoon:<[126 7].[139 19]>
/lib/push-hook/hoon:<[125 7].[139 19]>
poke failed from %contact-view on wire /join-group/ship/~dopzod/provider-standards-organization
poke-ack
/lib/push-hook/hoon:<[204 5].[208 84]>
/lib/push-hook/hoon:<[203 5].[208 84]>
/lib/push-hook/hoon:<[134 11].[134 32]>
/lib/push-hook/hoon:<[133 9].[135 21]>
/lib/push-hook/hoon:<[132 7].[139 19]>
/lib/push-hook/hoon:<[126 7].[139 19]>
/lib/push-hook/hoon:<[125 7].[139 19]>```

Here's my +trouble

```> +trouble
[ [%base-hash 0vb.3udn7.pmdp6.ncv05.pktvq.meu58.d08a2.mmk7e.t4e77.d62ka.bmhb4]
  [%home-hash 0v18.gi624.g0poi.0b8m7.sfpkm.033rt.qvn25.j025d.61lac.7o0id.fpqtm]
  [%kids-hash 0vb.3udn7.pmdp6.ncv05.pktvq.meu58.d08a2.mmk7e.t4e77.d62ka.bmhb4]
  [%glob-hash 0v3.cus8h.vc64c.rfb3t.22oji.b529a %done]
  [%our ship=~molten-magnum point='1108827828' life=[~ 2] rift=[~ 1]]
  [%sponsor ship=~worlur point='24244' life=[~ 2] rift=[~ 1]]
  [%dopzod ship=~dopzod point='4608' life=[~ 3] rift=[~ 2]]
  "Compare lifes and rifts to values here:"
  "https://etherscan.io/address/azimuth.eth#readContract"
  "  life - getKeyRevisionNumber"
  "  rift - getContinuityNumber"
  ~
]```

ooh my version is really old, have to fix this: Version 0.10.4

**Comment by matildepark** [comment]
Ping @liam-fitzgerald

**Comment by matildepark** [comment]
As an update there's a few fixes in the pipeline #3327 that may address this; it will deploy midweek by the latest.

**Comment by matildepark** [comment]
That fix is deployed — any better luck for you all?

**Comment by SaulMoonves** [comment]
I'm getting this, but I'm trying to verify with the person that invited me that it still exists:
```
poke failed from %contact-view on wire /join-group/ship/~dopzod/provider-standards-organization
poke-ack
/lib/push-hook/hoon:<[204 5].[208 84]>
/lib/push-hook/hoon:<[203 5].[208 84]>
/lib/push-hook/hoon:<[134 11].[134 32]>
/lib/push-hook/hoon:<[133 9].[135 21]>
/lib/push-hook/hoon:<[132 7].[139 19]>
/lib/push-hook/hoon:<[126 7].[139 19]>
/lib/push-hook/hoon:<[125 7].[139 19]>
```

**Comment by matildepark** [comment]
@liam-fitzgerald Would you mind continuing to troubleshoot here?

**Comment by SaulMoonves** [comment]
OK, the owner re-invited me and it let me in. So I don't have a problem after all.

**Comment by matildepark** [comment]
Ah ok. So that leaves @jamesacklin and @darbyn-litbel.

**Comment by mcferrenm** [comment]
@matildepark I ended up breaching. Thank you for following up.

**Comment by jamesacklin** [comment]
I got all the OTAs, and no longer see the error in my ship, but it does not appear I can join the group.

`:group-pull-hook +dbug` yields this:

```
[%0 tracking={[p=[entity=~bitbet-bolbel name=%urbit-community] q=~bitbet-bolbel]} inner-state=[#t/$~ q=0]]
```

**Comment by jamesacklin** [comment]
I still get the 0% tracking status, but I don't see the error I initially described. I'm in favor of closing this issue if it's also resolved for @darbyn-litbel

**Comment by senf-f** [comment]
Hi, I'm getting the same issue: when trying to join a group, everything just hangs for hours. I'm completely new to urbit, so I'm not sure what to do. This is the terminal output:
`loom: mapped 2048MB
lite: arvo formula 27e494c5
lite: core 7b144622       
lite: final state 7b144622
loom: mapped 2048MB
boot: protected loom
live: loaded: MB/450.756.608
vere: checking version compatibility
boot: installed 348 jets
ames: live on 56458
eyre: canceling ~[//http-server/0v1v.b9ms7/5/1]
eyre: canceling ~[//http-server/0v1v.b9ms7/4/1]
http: web interface live on http://localhost:80
http: loopback live on http://localhost:12321
pier (22321): live
ames: czar wet.urbit.org: ip .34.121.77.1
ames: czar zod.urbit.org: ip .35.247.119.159
[%e %authenticated-without-cookie]
[%e %authenticated-without-cookie]
[%e %authenticated-without-cookie]
[%e %authenticated-without-cookie]
[%e %authenticated-without-cookie]
[%e %authenticated-without-cookie]
[%e %authenticated-without-cookie]
[%e %authenticated-without-cookie]
out=[acked=%.y path=/resource/ver/ship/~hiddev-dannut/administration-5989/3]    
subscribe wire not unique
%graph-pull-hook
/helper/pull-hook/pull/resource/ship/~hiddev-dannut/administration-5989
[p=~hiddev-dannut q=%graph-push-hook]
error in %graph-pull-hook
%watch-not-unique
! subscribe wire not unique
! %graph-pull-hook
! /helper/pull-hook/pull/resource/ship/~hiddev-dannut/administration-5989
! [p=~hiddev-dannut q=%graph-push-hook]
[%e %authenticated-without-cookie]
[%e %authenticated-without-cookie]
>   [ [ %4
    prev-version=0
    prev-min-version=0
      tracking
    { [p=[entity=~zod name=%$] q=[ship=~zod status=[%sub-ver ver=0]]]
      [ p=[entity=~hatryx-lastud name=%other-life]
        q=[ship=~hatryx-lastud status=[%active ~]]
      ]
      [ p=[entity=~bitbet-bolbel name=%urbit-community]
        q=[ship=~bitbet-bolbel status=[%active ~]]
      ]
      [ p=[entity=~hiddev-dannut name=%new-hooniverse]
        q=[ship=~hiddev-dannut status=[%active ~]]
      ]
    }
    inner-state=[#t/* q=0]
  ]
  ~
]
> :group-pull-hook +dbug
>=
>   [ [ %4
    prev-version=0
    prev-min-version=0
      tracking
    { [p=[entity=~zod name=%$] q=[ship=~zod status=[%sub-ver ver=0]]]
      [ p=[entity=~hatryx-lastud name=%other-life]
        q=[ship=~hatryx-lastud status=[%active ~]]
      ]
      [ p=[entity=~bitbet-bolbel name=%urbit-community]
        q=[ship=~bitbet-bolbel status=[%active ~]]
      ]
      [ p=[entity=~hiddev-dannut name=%new-hooniverse]
        q=[ship=~hiddev-dannut status=[%active ~]]
      ]
    }
    inner-state=[#t/* q=0]
  ]
  ~
]`

Should I open a new issue?

**Comment by liam-fitzgerald** [comment]
`:group-pull-hook +kick, =nice |` should fix your issue

**Comment by senf-f** [comment]
Hey, that didn't help. This is my output:
```
> :group-pull-hook +kick, =nice |
>=
versioned nack for [entity=~hatryx-lastud name=%other-life] in %group-pull-hook 
watch-ack
/app/group-push-hook/hoon:<[125 3].[127 31]>
/app/group-push-hook/hoon:<[124 3].[127 31]>
/app/group-push-hook/hoon:<[122 3].[127 31]>
/app/group-push-hook/hoon:<[121 3].[127 31]>
/lib/push-hook/hoon:<[316 28].[316 72]>
/lib/push-hook/hoon:<[316 7].[316 73]>
/lib/push-hook/hoon:<[315 7].[316 73]>
/lib/push-hook/hoon:<[314 7].[316 73]>
/lib/push-hook/hoon:<[311 7].[316 73]>
/lib/push-hook/hoon:<[309 7].[316 73]>
/lib/push-hook/hoon:<[307 7].[316 73]>
/lib/push-hook/hoon:<[305 7].[316 73]>
/lib/push-hook/hoon:<[303 7].[316 73]>
/lib/push-hook/hoon:<[302 7].[329 9]>
/lib/push-hook/hoon:<[298 7].[329 9]>
/lib/push-hook/hoon:<[295 7].[329 9]>
/lib/push-hook/hoon:<[294 7].[329 9]>
/sys/vane/gall/hoon:<[1.360 9].[1.360 37]>
out=[acked=%.n path=/resource/ship/~hatryx-lastud/other-life]
subscribe wire not unique
%group-pull-hook
/helper/pull-hook/pull/unver-resource/ship/~hatryx-lastud/other-life
[p=~hatryx-lastud q=%group-push-hook]
error in %group-pull-hook
%watch-not-unique
! subscribe wire not unique
! %group-pull-hook
! /helper/pull-hook/pull/unver-resource/ship/~hatryx-lastud/other-life
! [p=~hatryx-lastud q=%group-push-hook]
versioned nack for [entity=~bitbet-bolbel name=%urbit-community] in %group-pull-
hook
watch-ack
/app/group-push-hook/hoon:<[125 3].[127 31]>
/app/group-push-hook/hoon:<[124 3].[127 31]>
/app/group-push-hook/hoon:<[122 3].[127 31]>
/app/group-push-hook/hoon:<[121 3].[127 31]>
/lib/push-hook/hoon:<[316 28].[316 72]>
/lib/push-hook/hoon:<[316 7].[316 73]>
/lib/push-hook/hoon:<[315 7].[316 73]>
/lib/push-hook/hoon:<[314 7].[316 73]>
/lib/push-hook/hoon:<[311 7].[316 73]>
/lib/push-hook/hoon:<[309 7].[316 73]>
/lib/push-hook/hoon:<[307 7].[316 73]>
/lib/push-hook/hoon:<[305 7].[316 73]>
/lib/push-hook/hoon:<[303 7].[316 73]>
/lib/push-hook/hoon:<[302 7].[329 9]>
[%e %authenticated-without-cookie]
[%e %authenticated-without-cookie]
; ~bitbet-bolbel is ok
[%e %authenticated-without-cookie]
~rilteg-hodsug:dojo> responding still trying
~rilteg-hodsug:dojo> |«behn»
```
I'm trying to join multiple groups, could that be the problem? I also have another ship booted on the same port app, maybe that is the problem?

**Comment by divdus-tarnus** [comment]
Been getting the same section back consistently while I have multiple group joins open:

subscribe wire not unique
%group-pull-hook

and haven't yet been able to join any of them (or fully abort the process). Not sure what to do either.
