### ISSUE TITLE
metadata-store not populating indices

### ISSUE THREAD

**Issue by timlucmiptev** [urbit/urbit#3568]
**Describe the bug**
In 0.1.50, `metadata-store` contains `associations` as before, but the `*-indices` maps are empty, which means I can't scry them.

This was not listed in the "Breaking Changes", and the fields are still in the state, so I assume this is unintended.

**To Reproduce**
1. Be me
2. Upgrade to the 0.1.50 OTA
3. Run `:metadata-store +dbug`
4. Observe empty `*-indices` maps

**Expected behavior**
Populated app/group/resource indices maps.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.6
 - Browser: Brave
 - Base hash: olu66

**Comment by Fang-** [comment]
This should have been fixed by #3566, which just went out over the network! Thanks for filing.

**Comment by timlucmiptev** [comment]
Unfortunately, it still isn't behaving correctly. My `app-indices` has only one entry in `%contacts`, 4 in `%chat`, and 1 in `%publish`, when in fact I have far more, and they're visible in `resource-indices`.

Relevant data from `dbug`:
https://pastebin.com/eu0sbN8y

**Comment by matildepark** [comment]
Do we know what’s going on? @Fang- @liam-fitzgerald Last night I left a group trying to get metadata back and now it is permanently saying it has no channels.

**Comment by matildepark** [comment]
Fixed in #3572.
