### ISSUE TITLE
^Z breaks input

### ISSUE THREAD

**Issue by chc4** [urbit/urbit#396]
By backgrounding and then returning to urbit via ^Z ^Z, the console output will fail to accept control characters like enter anymore, along with breaking linefeeds in console prints. I'm running Arch Linux with Urbit under urxvt, which is probably related. I assume it has something to do with setting terminal raw mode, like curses does. I'm not sure if this is actually a fixable issue, unfortunately...

**Comment by cahiggins** [comment]
Maybe this could be fixed by intercepting SIGTSTP somehow? I don't know too much about the term, I'll look into it more tomorrow.

**Comment by juped** [comment]
Yes, the one you can't intercept is kill -STOP, I think. Whatever you do, make it portable. :)

**Comment by cahiggins** [comment]
Will try my best, STOP and KILL you cant intercept but for (most) things you can intercept TSTP I believe. I'm not really familiar with any of the term handling code so it might be a few days, but like I said I'll see what I can do.

**Comment by ohAitch** [comment]
Fixed by #592 ?

**Comment by juped** [comment]
I mean, it's still broken. But it's a duplicate of #621 now.
