### ISSUE TITLE
Publish: read notes switch back to unread

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#4152]
**Describe the bug**
A couple of notes in the smol bibliotheca notebook in ~dasfeb/smol-computers show as unread. I mark them read but some time later they again show as unread

**Expected behavior**
read notes should stay read

**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser qutebrowser
 - Base hash o4o70

**Additional context**
Unsure how to reproduce

**Comment by mike-cr** [comment]
hmm this seems to occur after landscape says reconnecting and the terminal prints:

```
[%missing-subscription-in-unsubscribe '1607854544538-5ad539' 13]
[%missing-subscription-in-unsubscribe '1607854544538-5ad539' 15]
```

**Comment by mike-cr** [comment]
unsubscribing and resubscribing to the channel did not fix the problem, it eventually did the reconnecting thing, printed 
```
[%missing-subscription-in-unsubscribe '1607855186843-2a0ce1' 13]
[%missing-subscription-in-unsubscribe '1607855186843-2a0ce1' 15]
```
and again marked them unread

**Comment by liam-fitzgerald** [comment]
should be fixed by #4149

**Comment by mike-cr** [comment]
I've received the update, and I tried marking everything read in the problem channels to test if fixed but found the channel name remained bold despite no notes showing as new. I attempted to unsubscribe and resubscribe, but the channels didn't seem to unsubscribe properly - they're still listed in bold and when I click on them it just spinners endlessly. If I try hitting unsubscribe again it doesn't work and dojo prints:

```
/app/graph-store/hoon:<[284 7].[289 9]>
/app/graph-store/hoon:<[283 7].[289 9]>
/app/graph-store/hoon:<[282 7].[289 9]>
/app/graph-store/hoon:<[234 29].[234 54]>
/app/graph-store/hoon:<[232 5].[247 7]>
/app/graph-store/hoon:<[231 5].[247 7]>
/app/graph-store/hoon:<[230 5].[247 7]>
/app/graph-store/hoon:<[229 5].[617 7]>
/app/graph-store/hoon:<[228 5].[617 7]>
/app/graph-store/hoon:<[220 24].[220 60]>
/app/graph-store/hoon:<[219 5].[223 7]>
/app/graph-store/hoon:<[218 3].[224 15]>
/app/graph-store/hoon:<[217 3].[224 15]>
/app/graph-store/hoon:<[216 3].[791 5]>
/app/graph-store/hoon:<[215 3].[791 5]>
/sys/vane/gall/hoon:<[1.361 9].[1.361 37]>
```

**Comment by mike-cr** [comment]
ok I managed to resubscribe to the channels via the dojo, but unfortunately the OTA didn't fix the issue and the same notes are reverting to unread after being marked read

**Comment by mike-cr** [comment]
also, it seems that for one notebook, the unread count is 1 greater than the number of blue unread notes, and for the other it's 2 greater

**Comment by ryjm** [comment]
this is happening to me as well

**Comment by liam-fitzgerald** [comment]
This will occur on notes that have been edited, a fix is on the way
