### ISSUE TITLE
hark: unread status and count aren't removed after unsubscribing

### ISSUE THREAD

**Issue by mike-cr** [urbit/urbit#4164]
**Describe the bug**
I previously had a bug where a couple of notebooks would keep switching certain notes back to unread (see #4152). After the recent OTA, I tried to unsub/resub said notebooks and they got stuck in a state where they show in landscape as subscribed and having unread messages, but nothing loads when I click on them - just endless spinner. When I try to click unsub again nothing happens and the dojo prints:

```
/app/graph-store/hoon:<[284 7].[289 9]>
/app/graph-store/hoon:<[283 7].[289 9]>
/app/graph-store/hoon:<[282 7].[289 9]>
/app/graph-store/hoon:<[234 29].[234 54]>
/app/graph-store/hoon:<[232 5].[247 7]>
/app/graph-store/hoon:<[231 5].[247 7]>
/app/graph-store/hoon:<[230 5].[247 7]>
/app/graph-store/hoon:<[229 5].[617 7]>
/app/graph-store/hoon:<[228 5].[617 7]>
/app/graph-store/hoon:<[220 24].[220 60]>
/app/graph-store/hoon:<[219 5].[223 7]>
/app/graph-store/hoon:<[218 3].[224 15]>
/app/graph-store/hoon:<[217 3].[224 15]>
/app/graph-store/hoon:<[216 3].[791 5]>
/app/graph-store/hoon:<[215 3].[791 5]>
/sys/vane/gall/hoon:<[1.361 9].[1.361 37]>
```

**To Reproduce**
1. Unsure... if you had any notebooks that kept reverting to unread, try unsub those

**Expected behavior**
Should be able to unsub/resub channels normally

**Desktop (please complete the following information):**
 - OS: arch linux
 - Browser qutebrowser
 - Base hash 0v1i.m17tc.thht3.60qpc.bmknd.npdqk.8h3f1.luqj9.7k8ls.knqfs.u8adu

**Additional context**
see #4152

**Comment by tacryt-socryp** [comment]
This crash is occurring due to an assertion that states "in order to remove the graph in question, it must exist". The graph you are trying to remove does not exist, as it has been removed already.

**Comment by tacryt-socryp** [comment]
I'm unsure of what the issue is here with the spinner and not letting you resubscribe... Will think on this.

**Comment by mike-cr** [comment]
I tried unsubscribing from General chat in UC while it had unread messages and the same thing happened. It seems if you unsub any channel while unread it causes this problem

**Comment by ryjm** [comment]
yeah, it looks like if you unsub while unread, the group pane doesn't update the resource link with the `join` prefix, and so when you click on it it looks for a non-existent graph.

**Comment by JohnELester** [comment]
I'm seeing this same error.

**Comment by JohnELester** [comment]
I tried leaving the group and rejoining.  The stuck channel is still there.

**Comment by ryjm** [comment]
yeah there's a fix incoming - hark wasn't dismissing edit-notes properly i believe.

**Comment by ryjm** [comment]
oh wait that was a different issue - i did hear this was one was fixed as well though.

**Comment by JohnELester** [comment]
> I tried unsubscribing from General chat in UC while it had unread messages and the same thing happened. It seems if you unsub any channel while unread it causes this problem

I'm still seeing this problem.  Channels that I unsubscribed from while urnead are still stuck, spinning forever when I click on them.   I'm on `74m9v` base hash.

![111](https://user-images.githubusercontent.com/25461543/102677196-58af7080-416f-11eb-8735-f5d93ac031bf.png)


![222](https://user-images.githubusercontent.com/25461543/102677200-5baa6100-416f-11eb-83e2-98ba13cde224.png)

**Comment by matildepark** [comment]
Also can't leave Jobs + Gigs, also stuck forever.

**Comment by matildepark** [comment]
@tacryt-socryp Can you take a look at this this week?

**Comment by tacryt-socryp** [comment]
Yes, happy to.

**Comment by tacryt-socryp** [comment]
@matildepark I can't reproduce this issue with Jobs + Gigs. Is there any way I can take a look at your ship to figure out the issue?

**Comment by matildepark** [comment]
Changed title to reflect issue — the channel appears bold because on livenet we use hark as our source of truth for channel subscription status. But Hark doesn't clear unread counts when unsubscribing from a resource, so the channel "never unbolds", and Landscape's front-end thinks it's a valid resource, so it tries to render it instead of letting you join.

#4216 fixes the sidebar issue but shows a permanent `1 unread` with no bold items in the sidebar — because there is indeed 1 unread inside Hark.

**Comment by matildepark** [comment]
Fixed: #4216, #4261.
