### ISSUE TITLE
OTAs fail for 418 -> 415 - possibly all OTAs if many version behind

### ISSUE THREAD

**Issue by zalberico** [urbit/urbit#6385]
- Be on 418
- Attempt to OTA to 415
- Observe it run out of memory and crash

The work around: https://github.com/urbit/vere/issues/218#issuecomment-1426241417

The work around is to run those commands to only upgrade to 417 first and then the others. This is obviously not something a user should have to do.

Note that 417 is the groups 2 migration and 415 is doccords, but this shouldn't matter. The system should be smart about how it does OTAs to not always run out of memory.

My hypothesis is it's doing something dumb (trying to load everything in memory all at once for all the OTAs?)

**Comment by jalehman** [comment]
IIRC, this is fixed on the current release candidate that's going out next week. 

@matthew-levan fixed the strange page issue that'a responsible for this particular issue.

**Comment by matthew-levan** [comment]
This isn't completely fixed yet, but not sure it's worth having yet another issue for it. See https://github.com/urbit/vere/issues/234.

**Comment by zalberico** [comment]
I’m not convinced strange page is the cause of this failure. Why do we think that’s the case?

**Comment by matthew-levan** [comment]
> I’m not convinced strange page is the cause of this failure. Why do we think that’s the case?

The link above is a combo-issue for "strange page" and the 418 -> 415 OTA (also referred to as "guard page crash" because of the error messages).

I did re-run a 418 -> 415 OTA on a fakezod using Peter's new snapshot interface (which heavily reduces the amount of memory needed), and was actually able to retrieve a *Hoon* stack trace! Here it is: https://pastebin.com/wTX6gCSB

Looks like something with `dill`. BTW, `####` in the logs is Hoon's indicator for "failed to print stack trace".

**Comment by zalberico** [comment]
Thanks Matt - I think this is sufficiently different from the strange page that it should probably be tracked separately.
